from __future__ import annotations

from typing import Protocol

from src.domain.entities.models import BufferedEvent, DeadLetterEvent, ParameterEvent


class EventBuffer(Protocol):
    async def start(self) -> None: ...

    async def close(self) -> None: ...

    async def enqueue(self, event: ParameterEvent, error: str) -> None: ...

    async def get_due_events(self, limit: int) -> list[BufferedEvent]: ...

    async def mark_published(self, buffer_id: str) -> None: ...

    async def mark_failure(self, buffer_id: str, error: str) -> None: ...

    async def move_to_dead_letter(self, buffer_id: str, error: str) -> None: ...

    async def stats(self) -> dict[str, int]: ...

    async def dead_letters(self, limit: int = 100) -> list[DeadLetterEvent]: ...
